web:
  protected_access: true
  eshop_url: 'https://www.fantasyobchod.cz/asterion-moduly'
  menu_position_fixed: false
  show_home_button_on_homepage: true
  show_home_button_on_routes: true
  home_button_target: 'http://asterionrpg.cz/'
  name: 'HTML kostra pro Asterion moduly'
  title_smiley: ''
google:
  analytics_id: 'UA-121206931-0'
application:
  yaml_file_with_routes: 'routes.yml'