web:
  protected_access: true
  eshop_url: 'https://www.fantasyobchod.cz/asterion-moduly'
  menu_position_fixed: false
  menu:
    home_button:
      show_on_homepage: true
      show_on_routes: true
      target: 'http://asterionrpg.cz/'
  name: 'HTML kostra pro Asterion moduly'
  title_smiley: ''
google:
  analytics_id: 'UA-121206931-0'
application:
  yaml_file_with_routes: 'routes.yml'
