with_path_and_query:
  path: /{path}?{query}
tables:
  path: /{path}
  requirements:
    path: '(tabulky|tables)/*'
with_query:
  path: /?{query}
root:
  path: /{path}
  defaults:
    path: ''
    query: ''
